version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    environment:
      - TZ=Asia/Seoul
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/proxy.conf:/etc/nginx/nginx.conf
      - ./nginx-proxy/logs:/var/log/nginx-proxy/
  # nginx-server:
  #   container_name: nginx-server
  #   image: nginx:latest
  #   environment:
  #     - TZ=Asia/Seoul
  #   restart: always
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./php-source:/source
  #     - ./nginx-server/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx-server/logs:/var/log/nginx-server
  php-server:
    container_name: php-server
    image: study:v1 # 로컬 빌드 이미지 - Dockerfile docker build - t php73-study
    environment:
      - TZ=Asia/Seoul
    restart: always
    ports:
      - "8000:8000" #테스트 포트 라라벨
    expose:
      - "8000"
    volumes:
      - ./php-server:/source
